
-- 1. 创建枚举类型（如果尚未存在）
CREATE TYPE chatbot.vote_type AS ENUM ('good', 'average', 'poor');

-- 2. 创建 vote 表
CREATE TABLE chatbot.vote (
    vote_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    message_id BIGINT REFERENCES messages(id),
    vote_type vote_type NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW()
);