""" messages id to BIGINT

Revision ID: 3435bd80acd0
Revises: c6a6bc0cc430
Create Date: 2025-10-28 10:23:03.993912

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3435bd80acd0'
down_revision: Union[str, Sequence[str], None] = 'c6a6bc0cc430'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    #op.drop_index(op.f('idx_chatbot_qa_knowledge_fts'), table_name='qa_knowledge', postgresql_using='gin')
    #op.drop_index(op.f('idx_fts'), table_name='qa_knowledge', postgresql_using='gin')
    #op.drop_table('qa_knowledge')
    #op.drop_table('items')
    op.drop_table('messages')
   


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'messages', schema='chatbot', type_='foreignkey')
    op.create_foreign_key(op.f('messages_chat_id_fkey'), 'messages', 'chats', ['chat_id'], ['id'])
    op.alter_column('messages', 'id',
               existing_type=sa.BIGINT(),
               type_=sa.UUID(),
               existing_nullable=False,
               autoincrement=True)
    op.create_table('items',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('embedding', sa.NullType(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('items_pkey'))
    )
    op.create_table('qa_knowledge',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('question', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('category_level_1', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('category_level_2', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('category_level_3', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('content', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('q_embedding', sa.NullType(), autoincrement=False, nullable=True),
    sa.Column('a_embedding', sa.NullType(), autoincrement=False, nullable=True),
    sa.Column('reference', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('fts', postgresql.TSVECTOR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('qa_knowledge_pkey'))
    )
    op.create_index(op.f('idx_fts'), 'qa_knowledge', ['fts'], unique=False, postgresql_using='gin')
    op.create_index(op.f('idx_chatbot_qa_knowledge_fts'), 'qa_knowledge', ['fts'], unique=False, postgresql_using='gin')
    # ### end Alembic commands ###
