""" messages id to BIGINT

Revision ID: 45613fb44de5
Revises: 3435bd80acd0
Create Date: 2025-10-28 10:26:02.234682

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '45613fb44de5'
down_revision: Union[str, Sequence[str], None] = '3435bd80acd0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('messages',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('chat_id', sa.UUID(), nullable=True),
    sa.Column('message_role_enum', postgresql.ENUM('system', 'user', 'assistant', name='messageroleenum'), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('metadata_', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['chat_id'], ['chatbot.chats.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='chatbot'
    )
    # op.drop_index(op.f('idx_chatbot_qa_knowledge_fts'), table_name='qa_knowledge', postgresql_using='gin')
    # op.drop_index(op.f('idx_fts'), table_name='qa_knowledge', postgresql_using='gin')
    # op.drop_table('qa_knowledge')
    # op.drop_table('items')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('items',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('embedding', sa.NullType(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('items_pkey'))
    )
    op.create_table('qa_knowledge',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('question', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('category_level_1', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('category_level_2', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('category_level_3', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('content', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('q_embedding', sa.NullType(), autoincrement=False, nullable=True),
    sa.Column('a_embedding', sa.NullType(), autoincrement=False, nullable=True),
    sa.Column('reference', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('fts', postgresql.TSVECTOR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('qa_knowledge_pkey'))
    )
    op.create_index(op.f('idx_fts'), 'qa_knowledge', ['fts'], unique=False, postgresql_using='gin')
    op.create_index(op.f('idx_chatbot_qa_knowledge_fts'), 'qa_knowledge', ['fts'], unique=False, postgresql_using='gin')
    op.drop_table('messages', schema='chatbot')
    # ### end Alembic commands ###
