"""knowledge

Revision ID: 84bbec9a6e03
Revises: dc7c5932a14c
Create Date: 2025-11-04 12:42:35.399379

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '84bbec9a6e03'
down_revision: Union[str, Sequence[str], None] = 'dc7c5932a14c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('knowledge_catalog',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('category_level_1', sa.String(length=255), nullable=True),
    sa.Column('category_level_2', sa.String(length=255), nullable=True),
    sa.Column('category_level_3', sa.String(length=255), nullable=True),
    sa.Column('status', postgresql.ENUM('active', 'deleted', name='knowledgestatusenum'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='chatbot'
    )
    op.create_table('knowledge',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('knowledge_type', postgresql.ENUM('document', 'data_table', 'qa', name='knowledgetypeenum'), nullable=False),
    sa.Column('knowledge_catalog_id', sa.BIGINT(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('created_by', sa.BIGINT(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['knowledge_catalog_id'], ['chatbot.knowledge_catalog.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='chatbot'
    )
    op.create_table('knowledge_detail',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('knowledge_id', sa.BIGINT(), nullable=True),
    sa.Column('content', sa.TEXT(), nullable=True),
    sa.Column('status', postgresql.ENUM('active', 'deleted', name='knowledgestatusenum'), nullable=False),
    sa.Column('role', sa.String(length=255), nullable=True),
    sa.Column('version', sa.BIGINT(), nullable=True),
    sa.Column('created_by', sa.BIGINT(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['knowledge_id'], ['chatbot.knowledge.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='chatbot'
    )
    op.drop_index(op.f('idx_chatbot_qa_knowledge_fts'), table_name='qa_knowledge', postgresql_using='gin')
    op.drop_index(op.f('idx_fts'), table_name='qa_knowledge', postgresql_using='gin')
    op.drop_table('qa_knowledge')
    op.drop_table('doc_knowledge')
    op.drop_table('items')
    op.drop_constraint(op.f('message_context_chat_id_fkey'), 'message_context', type_='foreignkey')
    op.create_foreign_key(None, 'message_context', 'chats', ['chat_id'], ['id'], source_schema='chatbot', referent_schema='chatbot')
    op.drop_index(op.f('idx_chatbot_messages_chat_id'), table_name='messages')
    op.drop_constraint(op.f('messages_chat_id_fkey'), 'messages', type_='foreignkey')
    op.create_foreign_key(None, 'messages', 'chats', ['chat_id'], ['id'], source_schema='chatbot', referent_schema='chatbot')
    ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    #op.drop_constraint(None, 'messages', schema='chatbot', type_='foreignkey')
    #op.create_foreign_key(op.f('messages_chat_id_fkey'), 'messages', 'chats', ['chat_id'], ['id'])
    #op.create_index(op.f('idx_chatbot_messages_chat_id'), 'messages', ['chat_id'], unique=False)
    #op.drop_constraint(None, 'message_context', schema='chatbot', type_='foreignkey')
    #op.create_foreign_key(op.f('message_context_chat_id_fkey'), 'message_context', 'chats', ['chat_id'], ['id'])
    # op.create_table('items',
    # sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    # sa.Column('embedding', sa.NullType(), autoincrement=False, nullable=True),
    # sa.PrimaryKeyConstraint('id', name=op.f('items_pkey'))
    # )
    # op.create_table('doc_knowledge',
    # sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    # sa.Column('doc_id', sa.BIGINT(), autoincrement=False, nullable=True),
    # sa.Column('title', sa.TEXT(), autoincrement=False, nullable=True),
    # sa.Column('category_level_1', sa.TEXT(), autoincrement=False, nullable=True),
    # sa.Column('category_level_2', sa.TEXT(), autoincrement=False, nullable=True),
    # sa.Column('category_level_3', sa.TEXT(), autoincrement=False, nullable=True),
    # sa.Column('content', sa.TEXT(), autoincrement=False, nullable=False),
    # sa.Column('q_embedding', sa.NullType(), autoincrement=False, nullable=True),
    # sa.Column('a_embedding', sa.NullType(), autoincrement=False, nullable=True),
    # sa.Column('reference', sa.TEXT(), autoincrement=False, nullable=True),
    # sa.Column('fts', postgresql.TSVECTOR(), autoincrement=False, nullable=True),
    # sa.PrimaryKeyConstraint('id', name=op.f('doc_knowledge_pkey'))
    # )
    # op.create_table('qa_knowledge',
    # sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    # sa.Column('question', sa.TEXT(), autoincrement=False, nullable=True),
    # sa.Column('category_level_1', sa.TEXT(), autoincrement=False, nullable=False),
    # sa.Column('category_level_2', sa.TEXT(), autoincrement=False, nullable=True),
    # sa.Column('category_level_3', sa.TEXT(), autoincrement=False, nullable=True),
    # sa.Column('content', sa.TEXT(), autoincrement=False, nullable=False),
    # sa.Column('q_embedding', sa.NullType(), autoincrement=False, nullable=True),
    # sa.Column('a_embedding', sa.NullType(), autoincrement=False, nullable=True),
    # sa.Column('reference', sa.TEXT(), autoincrement=False, nullable=True),
    # sa.Column('fts', postgresql.TSVECTOR(), autoincrement=False, nullable=True),
    # sa.PrimaryKeyConstraint('id', name=op.f('qa_knowledge_pkey'))
    # )
    #op.create_index(op.f('idx_fts'), 'qa_knowledge', ['fts'], unique=False, postgresql_using='gin')
    #op.create_index(op.f('idx_chatbot_qa_knowledge_fts'), 'qa_knowledge', ['fts'], unique=False, postgresql_using='gin')
    op.drop_table('knowledge_detail', schema='chatbot')
    op.drop_table('knowledge', schema='chatbot')
    op.drop_table('knowledge_catalog', schema='chatbot')
    # ### end Alembic commands ###
