"""message to messages

Revision ID: c6a6bc0cc430
Revises: 99682eb9e4fc
Create Date: 2025-10-28 10:09:26.701839

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c6a6bc0cc430'
down_revision: Union[str, Sequence[str], None] = '99682eb9e4fc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('messages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('chat_id', sa.UUID(), nullable=True),
    sa.Column('message_role_enum', postgresql.ENUM('system', 'user', 'assistant', name='messageroleenum'), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('metadata_', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['chat_id'], ['chatbot.chats.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='chatbot'
    )
    op.drop_table('message')
    #op.drop_index(op.f('idx_chatbot_qa_knowledge_fts'), table_name='qa_knowledge', postgresql_using='gin')
    #op.drop_index(op.f('idx_fts'), table_name='qa_knowledge', postgresql_using='gin')
    #op.drop_table('qa_knowledge')
    #op.drop_table('items')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('items',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('embedding', sa.NullType(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('items_pkey'))
    )
    op.create_table('qa_knowledge',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('question', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('category_level_1', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('category_level_2', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('category_level_3', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('content', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('q_embedding', sa.NullType(), autoincrement=False, nullable=True),
    sa.Column('a_embedding', sa.NullType(), autoincrement=False, nullable=True),
    sa.Column('reference', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('fts', postgresql.TSVECTOR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('qa_knowledge_pkey'))
    )
    op.create_index(op.f('idx_fts'), 'qa_knowledge', ['fts'], unique=False, postgresql_using='gin')
    op.create_index(op.f('idx_chatbot_qa_knowledge_fts'), 'qa_knowledge', ['fts'], unique=False, postgresql_using='gin')
    op.create_table('message',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('chat_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('message_role_enum', postgresql.ENUM('system', 'user', 'assistant', name='messageroleenum'), autoincrement=False, nullable=False),
    sa.Column('content', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('metadata_', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['chat_id'], ['chats.id'], name=op.f('message_chat_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('message_pkey'))
    )
    op.drop_table('messages', schema='chatbot')
    # ### end Alembic commands ###
