"""initial migration

Revision ID: 99682eb9e4fc
Revises: 
Create Date: 2025-10-28 10:08:05.530815

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '99682eb9e4fc'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chats',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('status', postgresql.ENUM('active', 'deleted', name='chatstatusenum'), nullable=False),
    sa.Column('user_id', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='chatbot'
    )
    op.create_table('message',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('chat_id', sa.UUID(), nullable=True),
    sa.Column('message_role_enum', postgresql.ENUM('system', 'user', 'assistant', name='messageroleenum'), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('metadata_', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['chat_id'], ['chatbot.chats.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='chatbot'
    )
    # op.drop_index(op.f('idx_chatbot_qa_knowledge_fts'), table_name='qa_knowledge', postgresql_using='gin')
    # op.drop_index(op.f('idx_fts'), table_name='qa_knowledge', postgresql_using='gin')
    # op.drop_table('qa_knowledge')
    # op.drop_table('items')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### end Alembic commands ###
